from __future__ import annotations

from typing import Protocol


class ExecutionAdapter(Protocol):
    def discuss_and_spec(self, payload: object) -> object: ...
    def plan(self, payload: object) -> object: ...
    def run_dev(self, payload: object) -> object: ...
    def run_review(self, payload: object) -> object: ...
    def run_fix(self, payload: object) -> object: ...
    def finalize(self, payload: object) -> object: ...
